spring:
  application:
    name: game-stat

  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: 27017
      database: admin
      username: andersen
      password: andersen
      auto-index-creation: true

kafka:
  bootstrap-server: ${KAFKA_HOST:localhost:9092}
  consumer:
    group-id: 'game-stat'
    end-game-topic: 'end-game'